services:
# ====================================================================================================================
# APP
# ====================================================================================================================
  app:
    container_name: dev-javanews
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        JAVA_IMAGE: "21-jdk-bullseye"
        INSTALL_MAVEN: true
        INSTALL_GRADLE: false
        MAVEN_VERSION: "3.9.9"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 8080:8080
